# Generated by Django 3.0.1 on 2019-12-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.BooleanField(default=True),
        ),
    ]
